(function() {var implementors = {};
implementors["csound"] = [{text:"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/default/trait.Default.html\" title=\"trait core::default::Default\">Default</a> for <a class=\"struct\" href=\"csound/struct.ChannelHints.html\" title=\"struct csound::ChannelHints\">ChannelHints</a>",synthetic:false,types:["csound::channels::ChannelHints"]},{text:"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/default/trait.Default.html\" title=\"trait core::default::Default\">Default</a> for <a class=\"struct\" href=\"csound/struct.ChannelInfo.html\" title=\"struct csound::ChannelInfo\">ChannelInfo</a>",synthetic:false,types:["csound::channels::ChannelInfo"]},{text:"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/default/trait.Default.html\" title=\"trait core::default::Default\">Default</a> for <a class=\"struct\" href=\"csound/struct.OpcodeListEntry.html\" title=\"struct csound::OpcodeListEntry\">OpcodeListEntry</a>",synthetic:false,types:["csound::csound::OpcodeListEntry"]},{text:"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/default/trait.Default.html\" title=\"trait core::default::Default\">Default</a> for <a class=\"struct\" href=\"csound/struct.Csound.html\" title=\"struct csound::Csound\">Csound</a>",synthetic:false,types:["csound::csound::Csound"]},{text:"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/default/trait.Default.html\" title=\"trait core::default::Default\">Default</a> for <a class=\"struct\" href=\"csound/struct.CsAudioDevice.html\" title=\"struct csound::CsAudioDevice\">CsAudioDevice</a>",synthetic:false,types:["csound::rtaudio::CsAudioDevice"]},{text:"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/default/trait.Default.html\" title=\"trait core::default::Default\">Default</a> for <a class=\"struct\" href=\"csound/struct.CsMidiDevice.html\" title=\"struct csound::CsMidiDevice\">CsMidiDevice</a>",synthetic:false,types:["csound::rtaudio::CsMidiDevice"]},{text:"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/default/trait.Default.html\" title=\"trait core::default::Default\">Default</a> for <a class=\"struct\" href=\"csound/struct.RtAudioParams.html\" title=\"struct csound::RtAudioParams\">RtAudioParams</a>",synthetic:false,types:["csound::rtaudio::RtAudioParams"]},];

            if (window.register_implementors) {
                window.register_implementors(implementors);
            } else {
                window.pending_implementors = implementors;
            }
        
})()
